### ISSUE TITLE
Certain upstream hosts fail on download with OSX (osx-64 conda-forge issue)

### ISSUE THREAD

**Issue by bollwyvl** [prefix-dev/rattler-build#1608]
Noted on [conda-forge- zulip]([#general > Error only on OSX: Error downloading ftp.gnu.org/...](https://conda-forge.zulipchat.com/#narrow/channel/457337-general/topic/Error.20only.20on.20OSX.3A.20Error.20downloading.20ftp.2Egnu.2Eorg.2F.2E.2E.2E))
Some hosts are returning interesting HTTP errors during CI builds but only on OSX:

> https://github.com/conda-forge/less-feedstock/blob/26405d18edd59d71e08955e3dc64aff7cae58fe1/recipe/recipe.yaml

```
 ╭─ Running build for recipe: less-668-h8eb8b2c_1
 │
 │ ╭─ Fetching source code
 │ │ Fetching source from url: https://ftp.gnu.org/gnu/less/less-668.tar.gz
 │ │
 │ ╰─────────────────── (took 0 seconds)
 │
 ╰─────────────────── (took 0 seconds)
Error:   × Error downloading https://ftp.gnu.org/gnu/less/less-668.tar.gz: invalid
  │ HTTP version parsed


##[error]Bash exited with code '1'.
```

> https://github.com/conda-forge/fossil-feedstock/blob/7367da3c6e41de3ba5dff2a11a72808da9aebd0b/recipe/recipe.yaml#L15

Logs gone, got slightly further with a `400` response, and no further information.

I would say it's IP-based rate limiting in this brave new world of garbage scrapers, but it's not occuring on _other_ azure jobs. Perhaps it's some agent string?

**Comment by bollwyvl** [comment]
From the [zulip thread](https://conda-forge.zulipchat.com/#narrow/channel/457337-general/topic/Error.20only.20on.20OSX.3A.20Error.20downloading.20ftp.2Egnu.2Eorg.2F.2E.2E.2E/near/516002829), with access to both sides of the pipe:

> https://github.com/conda-forge/slepc-feedstock/pull/98#issuecomment-2849036055
>
> By looking at the server log files, the requests that fail appear as
>
> `"GET /download/distrib/slepc-3.23.1.tar.gz" 400 3322 "-" "-"`
> 
> while the successful requests appear as
>
> `"GET /download/distrib/slepc-3.23.1.tar.gz HTTP/1.1" 404 3691 "-" "Wget/1.25.0"`
>
> so it seems that it is the client's fault that is not specifying the protocol version in the query.

This is odd, as it looks like it is at least [_trying_ to set the user agent](https://github.com/prefix-dev/rattler-build/blob/v0.41.0/src/source/url_source.rs#L75), though I don't see anything to set the [version](https://docs.rs/reqwest/latest/reqwest/struct.RequestBuilder.html#method.version).

**Comment by minrk** [comment]
I just started testing this and bizarrely, it appears that only osx-64 builds of 0.41.0 are affected (of course that's all conda-forge mac builds), but I initially couldn't reproduce it when I started testing with native osx-arm64 builds of 0.41, but creating an emulated osx-64 env produces this error.

Is there any way to try to identify the differences between mac-x86_64 builds and mac-arm64 builds?

**Comment by wolfv** [comment]
Ah thanks, I also just started testing this and couldn't reproduce yet. Will try an emulated `rattler-build` as well.

**Comment by minrk** [comment]
it's a little hard to reproduce, since I can actually do a local x86_64 build of v0.41.0 and this issue doesn't occur, but it does on the same machine with `rattler-build=0.41.0=h05de357_0` from conda-forge. So there's something weird and nondeterministic in builds of 0.41.0, unless I'm doing something weird.

**Comment by wolfv** [comment]
Hmm, I have a test server in Python where I can log stuff and I do see the problem as mentioned (missing HTTP version) - first one is fine, second is broken osx-64 build:

```
=== Received Request ===
Raw request line: GET /invalidlicense-0.1.0.tar.gz HTTP/1.1
HTTP Version: HTTP/1.1
Command: GET
Path: /invalidlicense-0.1.0.tar.gz
Headers: {'user-agent': 'rattler-build/0.41.0', 'accept': '*/*', 'host': 'localhost:8000'}

"GET /invalidlicense-0.1.0.tar.gz HTTP/1.1" 200 0 "-" "rattler-build/0.41.0"

=== Received Request ===
Raw request line: GET /invalidlicense-0.1.0.tar.gz 
HTTP Version: HTTP/0.9
Command: GET
Path: /invalidlicense-0.1.0.tar.gz
Headers: {'user-agent': 'rattler-build/0.41.0', 'accept': '*/*', 'host': 'localhost:8000'}

"GET /invalidlicense-0.1.0.tar.gz " 200 0 "-" "rattler-build/0.41.0"
```


Test server: 

```py
from http.server import HTTPServer, BaseHTTPRequestHandler
import logging
import datetime
import sys

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(message)s',
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger('http_server')

class RequestLogger(BaseHTTPRequestHandler):
    def do_GET(self):
        # Log the request in a format similar to your server logs
        client_address = self.client_address[0]
        current_time = datetime.datetime.now().strftime('%d/%b/%Y:%H:%M:%S +0000')

        # Extract the raw request line to see exactly what the client sent
        request_line = self.requestline

        # Log in the format: "GET /path HTTP/1.1" status size "-" "User-Agent"
        user_agent = self.headers.get('User-Agent', '-')
        status_code = 200
        response_size = 0

        # Print detailed information about the request
        logger.info(f"\n=== Received Request ===")
        logger.info(f"Raw request line: {request_line}")
        logger.info(f"HTTP Version: {self.request_version}")
        logger.info(f"Command: {self.command}")
        logger.info(f"Path: {self.path}")
        logger.info(f"Headers: {dict(self.headers)}")

        # Log in the format similar to your server logs
        logger.info(f'\n"{request_line}" {status_code} {response_size} "-" "{user_agent}"')

        # Send a response
        self.send_response(status_code)
        self.send_header('Content-type', 'text/plain')
        self.end_headers()

        response = f"Received request: {request_line}\n"
        self.wfile.write(response.encode('utf-8'))

    def log_message(self, format, *args):
        # Suppress the default log messages
        return

def run_server(port=8000):
    server_address = ('', port)
    httpd = HTTPServer(server_address, RequestLogger)
    logger.info(f'Starting HTTP server on port {port}...')
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        logger.info('Server stopped by user')
    finally:
        httpd.server_close()

if __name__ == '__main__':
    run_server()
```

**Comment by wolfv** [comment]
Maybe it is in some way related to the old SDK that we use on macOS x86 ...

**Comment by minrk** [comment]
I don't understand how/where the default http version is specified in reqwest for http without https. I see there's ALPN, but that's TLS-only.

I actually can't find where `{VERB} {URL} {HTTP/VERSION}` bytes are written to figure out why `reqwests-middleware` has introduced this problem where straight use of `reqwests` doesn't have this problem.

We could set http 1.1 in the url source request with `.version(reqwest::Version::HTTP_11)`, or set it in the BaseClient `common_settings` with `ClientBuilder.http1_only()`. Both work for me, but since local emulated builds don't seem to introduce the problem, it's hard to say for sure that it is fixed. I can make it sent `HTTP/1.0` and that works.

**Comment by wolfv** [comment]
When I cross compile on Apple Silicon to Intel, I also get the error (using the exact recipe from conda-forge). I am debugging now with the conda-forge compilers.

**Comment by minrk** [comment]
fwiw, this patch _probably_ fixes it (and another issue setting user agent twice), but I can't seem to test: https://github.com/prefix-dev/rattler-build/compare/main...minrk:rattler-build:http?expand=1

**Comment by bollwyvl** [comment]
> this patch

Maybe the `tool_configuration` client factory should _always_ set the HTTP version?

**Comment by wolfv** [comment]
Unfortunately in my test, the patch didn't solve the issue. I exchanged the whole client with a simple `reqwest::Client` but even that didn't help. I then made a minimal test project, but could _not_ reproduce the issue anymore. So I am still a bit confused.

**Comment by minrk** [comment]
> Maybe the tool_configuration client factory should always set the HTTP version?

That would be adding `.http1_only()` to the client, as in #1623 . I'm not sure if that would work, since I don't understand the bug. I still can't find where reqwest sends the initial http line with the version or where the default value is set.

**Comment by wolfv** [comment]
Sadly it looks like this is a compiler bug: https://github.com/rust-lang/rust/issues/140686

I have just tried to use a different linker (`/usr/bin/ld`) but that fails with

```
...
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: ld: unknown options: -Wl,-rpath,/Users/wolfv/Programs/recipes/rattler-build-feedstock/output/bld/rattler-build_rattler-build_1747655646/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs 
```

I supppose we could try `mold` or `ld64`.

**Comment by wolfv** [comment]
We've fixed this issue for now in `conda-forge` by using the default linker. Hopefully it gets fixed on the Rust side, or Apple makes their linker re-distributable.
